#!/system/bin/sh
#Using original watch scripting from https://gist.github.com/mikesmullin/6401258
cmd1() {
sysrw
if [ -e /vendor/build.prop ]
	then
		sed -i '/debug.sf.nobootanimation=/d' /vendor/build.prop
fi

if [ $(getprop persist.sys.deso.bootanim) == "0" ]
	then
		echo "debug.sf.nobootanimation=1" >> /vendor/build.prop
	else
		echo "debug.sf.nobootanimation=0" >> /vendor/build.prop
fi

sysro
}

update_sha1() {
  sha1=`sha1sum $path1`
}

build1() {
  echo "Change detected; Invoking build command"
  cmd1
}

sha1=0
previous_sha1=$sha
path1=/data/property/persist.sys.deso.bootanim

while [ -z $(getprop persist.sys.deso.bootanim) ]
do
  sleep 1
done # waiting for boot complete

cmd1
echo "Boot Animation watcher is online"
update_sha1

compare() {
  update_sha1
  if [[ $sha1 != $previous_sha1 ]] ; then
    build1
    previous_sha1=$sha1
  fi
}
trap build SIGINT
trap exit SIGQUIT
while true; do
  compare
  sleep 1
done
